# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tasfaout Yassine
email: tasfaoutyassine@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Front-end developer, coffee lover. I design and code web apps,
  and in this blog/portfolio. You will find my latest works and articles,
  about the awesome web.
baseurl: "" # the subpath of your site, e.g. /blog
host : 0.0.0.0
url: "http://tasfaout.com" # the base hostname & protocol for your site
twitter_username: tasfaoutyassine
github_username: andelus
google_username: tasfaoutyassine
linkedin_username: tasfaout

# Permalinks settings
permalink: /:categories/:title

# Links in the website
links:
  - title: Let's meet
    url: /about
    icon: ion-ios-people-outline
  - title: Super Powers
    url: /skills
    icon: ion-ios-flask-outline
  - title: Articles
    url: /articles
    icon: ion-ios-bookmarks-outline
  - title: Projects
    url: /projects
    icon: ion-ios-lightbulb-outline
  - title: Say Hello
    url: /contact
    icon: ion-ios-chatbubble-outline

# Plugins
gems:
  - jekyll-compass
  - jekyll-assets


# Build settings
markdown: kramdown
